- Gemfile
- Gemfile.lock
- db/seeds.rb
Improved seed file.
Now just creates trip estimates between just European cities.
Users allocated to European cities only (France, UK, Italy, Spain and Germany)
Used Geokit Gem to calculate Haversine distance between cities to estimate flight time.
Flight time calculated on the basis of avg 500km/h planes with adjustments for short flights to be a min of 45 mins.
Est prices based on distance (£1/mile) tweaked by random factors.
> Used Geokit to measure distance and calc est time between cities

- app/controllers/trips_controller.rb
- app/models/trip.rb
- app/policies/trip_policy.rb
- app/views/trips/index.html.erb
- app/views/trips/new.html.erb
* Removed dates and city location from trip creation form
* tweaked `show?` policy for Trips to only allow viewing of trips on which you participate
* Add `has_many :users` to `Trip` model
* Made trip list item on index page a link to the trip
> fixes to creation of new trips

- app/controllers/application_controller.rb
- app/helpers/meta_tags_helper.rb
- app/views/layouts/application.html.erb
- config/initializers/default_meta.rb
- config/meta.yml
I think I've done this right but tbh I just copied and pasted stuff from [here](https://www.lewagon.com/blog/setup-meta-tags-rails)
> Add og tags

- public/404.html
- public/500.html
Just some simple error pages to get us across the line.
> Custom 505 & 400 Done

- README.md
- app/assets/stylesheets/application.scss
- app/javascript/components/select2.js
Fingers crossed this does the trick
> fixed select2 issue and added info to readme about .env for cloudinary

- app/javascript/components/select2.js
- app/views/layouts/application.html.erb
> attempted select2 bugfix

- app/views/trips/index.html.erb
Link to view preferences, wasn't working so I dummied it, as it needs a route too.
Not sure what the plans were for that, so I dummied it.
> Dummied view reference link to make screen work @gareth

- app/views/pages/home.html.erb
- app/views/shared/_footer.html.erb
Just a few merge commits and a few more front end tweaks - nothing sensational.
> Landing page

- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/controllers/participant_scores_controller.rb
- app/helpers/star_rating_helper.rb
- app/views/participant_scores/index.html.erb
- app/views/shared/_navbar.html.erb
- tweaks to navbar
- increase button rounding in line with Figma
> Tidy up Navbar a little

- app/controllers/participant_scores_controller.rb
- app/helpers/star_rating_helper.rb
- app/views/participant_scores/index.html.erb
App no longer errors when viewing participant scores if the sidekiq job has not been run
> Check scoring attachment

- app/controllers/participant_scores_controller.rb
- app/javascript/controllers/sort_controller.js
- app/views/participant_scores/index.html.erb
- db/migrate/20210314184920_add_veto_to_participant_score.rb
- db/schema.rb
Better to explicitly store the veto of a participant because position attribute is totally under control of 'acts_as_list' gem.
Could keep it as a negative score but make things a little more complicated.
This PR all adds the AJAX, which is now semi working, albiet I've got to nail how to retrieve dataset values when user presses between the fontawesoom icon or edge of button. Needs further reading on Stimulus.
> Added Veto attribute to Participant Score

- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
- app/views/trips/index.html.erb
Just a few stray items on the landing etc.  Nothing major.
> Frontend fixups 😒

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_warning.scss
- app/views/pages/home.html.erb
Simple red pop-up on the landing page - with link & dismiss.
> A COVID19 Travel policy pop-up 🎉

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
Check it out! Does it feel like a real business yet @akilchomoko ?
> I made us a pricing strategy 😅

- app/assets/stylesheets/components/_navbar.scss
- app/controllers/application_controller.rb
- app/helpers/avatar_helper.rb
- app/views/shared/_navbar.html.erb
Now, the default avatar for a user is a purple circle with their initials in it:
> added avatar helper to create default avatar using initials

- app/assets/stylesheets/components/_card_rank.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/participant_scores_controller.rb
- app/javascript/controllers/sort_controller.js
- app/views/participant_scores/index.html.erb
Got the veto buttons and code working.
Also disabled ranking once they have submitted.
Remain - ability to only veto one record
> Veto Buttons

- app/assets/stylesheets/components/_citycardlist.scss
- app/assets/stylesheets/components/_index.scss
- app/views/potential_destinations/index.html.erb
Image to widen. 
Icons to align (maybe change to purple)
> Potential destinations css - grid for cards & text formatting

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_text.scss
- app/views/pages/home.html.erb
- app/views/trips/index.html.erb
Resolved some merge clashes etc.
> Minor Front-endy stuff 🚀

- app/views/potential_destinations/index.html.erb
> added styling to buttons

- app/assets/stylesheets/components/_citycardlist.scss
- app/views/potential_destinations/index.html.erb
Update on the size of the div needed for placement of the heart icon
> small update on div of heart icon 

- app/assets/stylesheets/components/_highlight.scss
- app/assets/stylesheets/components/_index.scss
- app/views/devise/sessions/new.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_footer-small.html.erb
- app/views/shared/_navbar.html.erb
> Lunchtime Frontend Fun ☘

- app/views/trips/index.html.erb
> Plus symbol added on trips page directing to create trip

- app/assets/stylesheets/components/_card_rank.scss
- app/assets/stylesheets/components/_citycardlist.scss
- app/controllers/participant_scores_controller.rb
- app/controllers/potential_destinations_controller.rb
- app/helpers/star_rating_helper.rb
- app/javascript/controllers/love_controller.js
- app/models/trip.rb
- app/views/participant_scores/index.html.erb
- app/views/potential_destinations/index.html.erb
- config/application.rb
Quite a large PR.
Guidance done (except for dates)
Duplicate check
Veto Button
Love Button
Submitted Symbol
Correct currency
Picture correction on potential destinations
Text positioning
> Proper ratings for distance, time, budget

- app/assets/stylesheets/components/_plus.scss
- app/views/trips/index.html.erb
@WaynePatrickDalton Made the trip index page more figma-y. Feel free to decline if you were going in a different direction for the page
> Csschanges

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_inspiration.scss
- app/assets/stylesheets/components/_tripcardimage.scss
- app/views/trips/index.html.erb
> Trips page - inspirational content

- app/assets/stylesheets/components/_citycardlist.scss
- app/controllers/potential_destinations_controller.rb
- app/controllers/trip_participants_controller.rb
- app/javascript/controllers/pref_controller.js
- app/javascript/controllers/search_controller.js
- app/policies/trip_participant_policy.rb
- app/views/potential_destinations/index.html.erb
- package.json
- yarn.lock
Slider JS
Date Preferences JS
Budget and Time Defaults
Search Formating
A lot of hair pulling
> Potential Destinations

- app/policies/trip_participant_policy.rb
- app/views/trips/show.html.erb
Now you needn't fear clicking 'delete' during the demo 😄
> Change tp delete policy

- app/models/trip.rb
- app/views/trips/show.html.erb
Fixed error which occurred during demoing
> Fix date error

- app/assets/stylesheets/components/_city_selector.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/trips_controller.rb
- app/views/trips/show.html.erb
City selection is now a choice of 3
> Cities summary for finalise

- app/assets/stylesheets/components/_card_rank.scss
- app/views/pages/home.html.erb
- app/views/participant_scores/index.html.erb
@akilchomoko - I changed the type of a button, and it causes an error on you AJAX - am merging - but you will need to help me fix it.
> Ranking Page - Front end. 

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/pages/_home.scss
- app/controllers/trips_controller.rb
- app/views/participant_scores/index.html.erb
- app/views/shared/_container.html.erb
- app/views/shared/_footer-medium.html.erb
- app/views/trips/show.html.erb
Made the trip show page look a little less terrible
> Trip show page cleanup

- app/jobs/improve_photos_job.rb
- app/views/layouts/application.html.erb
For Paris, Madrid, London (LHR), Alpe d Huez, Lisbon and Berlin
> Improve photos job

- app/views/participant_scores/index.html.erb
> add missing end
